swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /comentario/:
    get:
      tags:
      - comentario
      description: get Comentario
      operationId: ComentarioController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Comentario'
        "403": {}
    post:
      tags:
      - comentario
      description: create Comentario
      operationId: ComentarioController.Post
      parameters:
      - in: body
        name: body
        description: body for Comentario content
        required: true
        schema:
          $ref: '#/definitions/models.Comentario'
      responses:
        "201":
          description: '{int} models.Comentario'
        "403":
          description: body is empty
  /comentario/{id}:
    get:
      tags:
      - comentario
      description: get Comentario by id
      operationId: ComentarioController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Comentario'
        "403":
          description: :id is empty
    put:
      tags:
      - comentario
      description: update the Comentario
      operationId: ComentarioController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Comentario content
        required: true
        schema:
          $ref: '#/definitions/models.Comentario'
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Comentario'
        "403":
          description: :id is not int
    delete:
      tags:
      - comentario
      description: delete the Comentario
      operationId: ComentarioController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /galeria/:
    get:
      tags:
      - galeria
      description: get Galeria
      operationId: GaleriaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Galeria'
        "403": {}
    post:
      tags:
      - galeria
      description: create Galeria
      operationId: GaleriaController.Post
      parameters:
      - in: body
        name: body
        description: body for Galeria content
        required: true
        schema:
          $ref: '#/definitions/models.Galeria'
      responses:
        "201":
          description: '{int} models.Galeria'
        "403":
          description: body is empty
  /galeria/{id}:
    get:
      tags:
      - galeria
      description: get Galeria by id
      operationId: GaleriaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Galeria'
        "403":
          description: :id is empty
    put:
      tags:
      - galeria
      description: update the Galeria
      operationId: GaleriaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Galeria content
        required: true
        schema:
          $ref: '#/definitions/models.Galeria'
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Galeria'
        "403":
          description: :id is not int
    delete:
      tags:
      - galeria
      description: delete the Galeria
      operationId: GaleriaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /tecnica/:
    get:
      tags:
      - tecnica
      description: get Tecnica
      operationId: TecnicaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Tecnica'
        "403": {}
    post:
      tags:
      - tecnica
      description: create Tecnica
      operationId: TecnicaController.Post
      parameters:
      - in: body
        name: body
        description: body for Tecnica content
        required: true
        schema:
          $ref: '#/definitions/models.Tecnica'
      responses:
        "201":
          description: '{int} models.Tecnica'
        "403":
          description: body is empty
  /tecnica/{id}:
    get:
      tags:
      - tecnica
      description: get Tecnica by id
      operationId: TecnicaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Tecnica'
        "403":
          description: :id is empty
    put:
      tags:
      - tecnica
      description: update the Tecnica
      operationId: TecnicaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Tecnica content
        required: true
        schema:
          $ref: '#/definitions/models.Tecnica'
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.Tecnica'
        "403":
          description: :id is not int
    delete:
      tags:
      - tecnica
      description: delete the Tecnica
      operationId: TecnicaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Comentario:
    title: Comentario
    type: object
    properties:
      Asunto:
        type: string
      Cuerpo:
        type: string
      Fecha:
        type: string
      Id:
        type: integer
        format: int64
  models.Galeria:
    title: Galeria
    type: object
    properties:
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Imagen:
        type: string
      Restaurante:
        type: string
      Titulo:
        type: string
  models.Tecnica:
    title: Tecnica
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Imagen:
        type: string
      Info:
        type: string
      Titulo:
        type: string
      Url:
        type: string
tags:
- name: comentario
  description: |
    ComentarioController operations for Comentario
- name: galeria
  description: |
    GaleriaController operations for Galeria
- name: tecnica
  description: |
    TecnicaController operations for Tecnica
